export const FeedbackList = [
  {
    id: 1,
    description: 'feedbackText4',
    video_url: '/videos/davPolycVideo.mp4',
    videoIcon: '/images/uploads/davityantsfeedbackImage2.png',
    image: '/images/uploads/feedback1.png',
    directorName: 'feedBackDirectorName4',
    director: 'Director Davidyants polyclinics',
    isVideo: true,
  },
  {
    id: 2,
    description: 'feedbackText1',
    video_url: '/images/uploads/moulkfeedback.png',
    videoIcon: '',
    image: '/images/uploads/feedback1.png',
    directorName: 'feedBackDirectorName2',
    director: 'Founder of Moulk',
    isVideo: false,
  },
  {
    id: 3,
    description: 'feedbackText2',
    video_url: '/images/uploads/mallsfeedback.png',
    videoIcon: '',
    image: '/images/uploads/feedback2.png',
    directorName: 'feedBackDirectorName3',
    director: 'Founder of Malls',
    isVideo: false,
  },
  {
    id: 4,
    description: 'feedbackText3',
    video_url: '/videos/davlabVideo.mp4',
    videoIcon: '/images/uploads/davityancfeedbackImage.png',
    image: '/images/uploads/feedbackdavlab.jpg',
    directorName: 'feedBackDirectorName',
    director: 'director',
    isVideo: true,
  },
];
