import Author from '../../../../../public/images/uploads/feedbackAuthor.png';

export const ourBlogList = [
  {
    id: 1,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 2,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 3,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 4,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 5,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 6,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 7,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 8,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 9,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 10,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 11,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 12,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 13,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 14,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 15,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 16,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 17,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 18,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 19,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 20,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 21,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 22,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 23,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 24,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
  {
    id: 25,
    title: 'blogTitle',
    authorImage: { Author },
    category: 'blogCategoryDesign',
    authorName: 'blogAuthorName',
    date: 'blogDate',
    description: 'blogDescription',
  },
];
