export const teamList = [
  {
    id: 1,
    teamMember: '/images/team/haykpetrosyan.png',
    name: 'Hayk Petrosyan',
    profession: 'Co founder and CEO',
  },
  {
    id: 2,
    teamMember: '/images/team/akakachatryan.png',
    name: 'Arkadi ',
    profession: 'Co founder and CTO',
  },
  {
    id: 36,
    teamMember: '/images/team/haykpetrosyangermany.png',
    name: 'Hayk Petrosyan ',
    profession: 'International representative in Germany',
  },
  {
    id: 37,
    teamMember: '/images/global/team-member.png',
    name: 'Jack Harrison',
    profession: 'International representative in USA',
  },

  {
    id: 4,
    teamMember: '/images/team/levyesayan.png',
    name: 'Lev Yesayan',
    profession: 'Front-end TeamLead',
  },
  {
    id: 5,
    teamMember: '/images/team/saqshiqikchyan.png',
    name: 'Saqo Shirikchyan',
    profession: 'PHP TeamLead',
  },
  {
    id: 6,
    teamMember: '/images/team/vardadami.png',
    name: 'Vard Adami',
    profession: 'UI/UX Design TeamLead',
  },
  {
    id: 7,
    teamMember: '/images/team/armanasatryan.png',
    name: 'Arman Astaryan',
    profession: 'Front-end Developer',
  },
  {
    id: 8,
    teamMember: '/images/team/narekavagyan.png',
    name: 'Narek Avagyan',
    profession: 'UI Developer',
  },
  {
    id: 9,
    teamMember: '/images/team/suskotoshyan.png',
    name: 'Sus Kotoshyan',
    profession: 'Project Manager',
  },
  {
    id: 10,
    teamMember: '/images/team/naneghazaryan.png',
    name: 'Nane Ghazaryan',
    profession: 'QA Specialist',
  },
  {
    id: 11,
    teamMember: '/images/team/edwardgabrielyan.png',
    name: 'Edvard Gabrielyan',
    profession: 'Front-end Developer',
  },
  {
    id: 12,
    teamMember: '/images/team/lusinemanukyan.png',
    name: 'Lusine  Manukyan',
    profession: 'Graphic Designer',
  },
  {
    id: 13,
    teamMember: '/images/team/narekgevorgyan.png',
    name: 'Narek Gevorgyan',
    profession: 'Front-end Developer',
  },
  {
    id: 14,
    teamMember: '/images/team/karenharutyunyan.png',
    name: 'Karen Harutyunyan',
    profession: 'Front-end Developer',
  },
  {
    id: 15,
    teamMember: '/images/team/abulstepanyan.png',
    name: 'Abo Stepanyan',
    profession: 'Front-end Developer',
  },
  {
    id: 16,
    teamMember: '/images/team/andoterteryan.png',
    name: 'Andranik Terteryan ',
    profession: 'UI Developer',
  },
  {
    id: 17,
    teamMember: '/images/team/gevkirakosyan.png',
    name: 'Gevorg Kirakosyan',
    profession: 'Front-end Developer',
  },
  {
    id: 18,
    teamMember: '/images/team/gorsimonyan.png',
    name: 'Gor Simonyan',
    profession: 'Backend Developer',
  },
  {
    id: 19,
    teamMember: '/images/team/karensayadyan.png',
    name: 'Karen Sayadyan',
    profession: 'Backend Developer',
  },
  {
    id: 20,
    teamMember: '/images/team/sussahakyan.png',
    name: 'Susanna Sahakyan',
    profession: 'Graphic Designer',
  },
  {
    id: 21,
    teamMember: '/images/team/miqokarapetyan.png',
    name: 'Miqayel Grigoryan ',
    profession: 'Front-end Developer',
  },
  {
    id: 22,
    teamMember: '/images/team/gagpetrosyan.png',
    name: 'Gagik Petrosyan',
    profession: 'Backend Developer',
  },
  {
    id: 23,
    teamMember: '/images/team/hovmalxasyan.png',
    name: 'Hovo Malkhasyan',
    profession: 'Front-end Developer',
  },
  {
    id: 24,
    teamMember: '/images/team/milenagoginyan.png',
    name: 'Milena Goginyan',
    profession: 'Graphic Designer',
  },
  {
    id: 25,
    teamMember: '/images/team/narekatabekyan.png',
    name: 'Narek Atabekyan',
    profession: 'Full-Stack Developer',
  },
  {
    id: 26,
    teamMember: '/images/team/arturheroyan.png',
    name: 'Artur Hepoyan',
    profession: 'Backend Developer',
  },
  {
    id: 27,
    teamMember: '/images/team/gagbaghdasaryan.png',
    name: 'Gagik Baghdasaryan',
    profession: 'Front-end Developer',
  },
  {
    id: 28,
    teamMember: '/images/team/serojivanyan.png',
    name: 'Seroj  Ivanyan',
    profession: 'Backend Developer',
  },
  {
    id: 29,
    teamMember: '/images/team/vanovasilyan.png',
    name: 'Vano Vasilyan',
    profession: 'Front-end Developer',
  },
  {
    id: 30,
    teamMember: '/images/team/hovgasparyan.png',
    name: 'Hovik Gasparyan',
    profession: 'Front-end Developer',
  },
  {
    id: 31,
    teamMember: '/images/team/aramzhakaryan.png',
    name: 'Aram Zakharyan',
    profession: 'Front-end Developer',
  },
  {
    id: 32,
    teamMember: '/images/team/davyaloyan.png',
    name: 'David Yayloyan',
    profession: 'Backend Developer',
  },
  {
    id: 33,
    teamMember: '/images/team/gagikmanukyan.png',
    name: 'Gagik Manukyan',
    profession: 'Front-end Developer',
  },
  {
    id: 34,
    teamMember: '/images/team/narekdem.png',
    name: 'Narek Demirchyan',
    profession: 'Front-end Developer',
  },
  {
    id: 35,
    teamMember: '/images/team/vazgen.png',
    name: 'Vazgen Zadayan',
    profession: 'Front-end Developer',
  },
];
